# camera_server.yaml
camera:
  depth:
    width: 640
    height: 480
    format: z16
    fps: 30
  color:
    width: 640
    height: 480
    format: bgr8
    fps: 30

server:
  host: "0.0.0.0"
  port: 8080